# Generated by Django 5.1.3 on 2024-11-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_telegramauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
