# Generated by Django 5.1.3 on 2024-11-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser')),
            ],
        ),
    ]
