# Generated by Django 5.1.3 on 2024-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
