# Generated by Django 5.1.3 on 2024-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
