# Generated by Django 5.1.3 on 2024-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_location_group_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
    ]
